import time
import RPi.GPIO as GPIO

A = 31
B = 32
C = 33
D = 35
delay = 0.5
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BOARD)
GPIO.setup(A, GPIO.OUT)
GPIO.setup(B, GPIO.OUT)
GPIO.setup(C, GPIO.OUT)
GPIO.setup(D, GPIO.OUT)
while True:
    GPIO.output(A, GPIO.LOW)
    GPIO.output(B, GPIO.LOW)
    GPIO.output(C, GPIO.LOW)
    GPIO.output(D, GPIO.LOW)
    time.sleep(delay)
    GPIO.output(A, GPIO.HIGH)
    GPIO.output(B, GPIO.LOW)
    GPIO.output(C, GPIO.LOW)
    GPIO.output(D, GPIO.LOW)
    time.sleep(delay)
    GPIO.output(A, GPIO.LOW)
    GPIO.output(B, GPIO.HIGH)
    GPIO.output(C, GPIO.LOW)
    GPIO.output(D, GPIO.LOW)
    time.sleep(delay)
    GPIO.output(A, GPIO.HIGH)
    GPIO.output(B, GPIO.HIGH)
    GPIO.output(C, GPIO.LOW)
    GPIO.output(D, GPIO.LOW)
    time.sleep(delay)
    GPIO.output(A, GPIO.LOW)
    GPIO.output(B, GPIO.LOW)
    GPIO.output(C, GPIO.HIGH)
    GPIO.output(D, GPIO.LOW)
    time.sleep(delay)
    GPIO.output(A, GPIO.HIGH)
    GPIO.output(B, GPIO.LOW)
    GPIO.output(C, GPIO.HIGH)
    GPIO.output(D, GPIO.LOW)
    time.sleep(delay)
    GPIO.output(A, GPIO.LOW)
    GPIO.output(B, GPIO.HIGH)
    GPIO.output(C, GPIO.HIGH)
    GPIO.output(D, GPIO.LOW)
    time.sleep(delay)
    GPIO.output(A, GPIO.HIGH)
    GPIO.output(B, GPIO.HIGH)
    GPIO.output(C, GPIO.HIGH)
    GPIO.output(D, GPIO.LOW)
    time.sleep(delay)
    GPIO.output(A, GPIO.LOW)
    GPIO.output(B, GPIO.LOW)
    GPIO.output(C, GPIO.LOW)
    GPIO.output(D, GPIO.HIGH)
    time.sleep(delay)
    GPIO.output(A, GPIO.HIGH)
    GPIO.output(B, GPIO.LOW)
    GPIO.output(C, GPIO.LOW)
    GPIO.output(D, GPIO.HIGH)
    time.sleep(delay)
